def animais():
    animal =['TARTARUGA','ELEFANTE','ABELHA','ZEBRA','LEOPARDO','OVELHA','PAPAGAIO','MACACO','BALEIA','COALA' ]
    return animal

def filmes():
    filmes=['PIRATAS DO CARIBE','O REI LEAO','CONTRA O TEMPO','VINGADORES','AQUAMAN','HOMEM ARANHA','STAR WARS','HOMEM DE FERRO','MADAGASCAR','BATMAN' ]
    return filmes

def desenhos():
    desenhos=['ONE PIECE', 'RICK AND MORTY','DRAGON BALL','POKEMON','BEN 10','DIGIMON','JOHNNY BRAVO','HORA DE AVENTURA','SIMPSONS','NARUTO']
    return desenhos

def series():
    seriados=['CASTLEVANIA','VIKINGS','BREAKING BAD','STRANGER THINGS','GAME OF THRONES','PRISON BREAK','UMBRELLA ACADEMY','LOST','SUPERNATURAL','THE GOOD DOCTOR']
    return seriados

def games():
    games=['RAINBOW SIX SIEGE','PRINCE OF PERSIA','THE WITCHER','LEAGUE OF LEGENDS','COUNTER STRIKE','OVERWATCH','GRAND CHASE','GRAND THEFT AUTO','LEFT 4 DEAD','BIOSHOCK']
    return games
